# Simple install with
# mamba env create -f environment.yml
name: myria3d
channels:
  - pytorch
  - nvidia
  - pyg
  - comet_ml
  - conda-forge
  - anaconda
dependencies:
  - python=3.12
  - pip
  # --------- Deep Learning --------- #
  - pytorch::pytorch==2.4.1
  - pytorch::pytorch-cuda
  - pytorch::torchvision
  - conda-forge::lightning
  - conda-forge::torchmetrics
  - pyg::pyg
  - pyg::pytorch-cluster
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - anaconda:mkl==2022.*
  # Troubleshooting: if libcusparse.so.11. errors occur, run
  # export LD_LIBRARY_PATH="/home/${USER}/miniconda/envs/lib:$LD_LIBRARY_PATH"
  # ou
  # export LD_LIBRARY_PATH="/home/${USER}/anaconda3/envs/lib:$LD_LIBRARY_PATH"
  # see https://github.com/pyg-team/pytorch_geometric/issues/2040#issuecomment-766610625
  # --------- data formats --------- #
  - numpy
  - h5py
  # --------- geo --------- #
  - pdal==2.10.*
  - python-pdal
  - conda-forge:gdal
  - conda_forge:pyproj
  - laspy
  # --------- loggers --------- #
  - comet_ml::comet_ml
  - conda-forge::urllib3<2 # To solve for https://github.com/GeneralMills/pytrends/issues/591
    # --------- Visualization --------- #
  - pandas
  - matplotlib
  - seaborn # used in some callbacks
  # --------- parameters handling --------- #
  - hydra-core
  - hydra-colorlog
  # --------- linters --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  # --------- tests --------- #
  - pytest
  - coverage
  - pytest-cov
  # --------- others --------- #
  - python-dotenv # loading env variables from .env file
  - rich # beautiful text formatting in terminal
  - sh # for running bash commands in some tests
  - pudb # debugger
  - twine # to publish pip package
    # # --------- Documentation --------- #
  - sphinx
  - recommonmark
  - sphinx_rtd_theme
  - docutils
  - rstcheck
  - pip:
      # --------- Documentation --------- #
      - myst_parser
      - sphinxnotes-mock
      - sphinx_paramlinks
      - ign-pdal-tools==1.16.0
