defaults:
  - default.yaml

lr: 0.003933709606504788   # 200-long LR-test-range betw 10^-4 and 3.0

neural_net_class_name: "PointNet"
neural_net_hparams:
  num_features: ${model.d_in}  # 3 (xyz) + num of features
  num_classes: ${model.num_classes}
  subsample: 4096
