# Workflow name
name: "Documentation Build"

on:
  push:
    branches:
      - main

  # UNCOMMENT TO DEBUG DOCUMENTATION
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Use bash instead of sh for conda activation
    defaults:
      run:
        shell: bash -l {0}

    # Task to do when launching the workflow
    steps:
      # 1. First get the repository source

      - name: "Checkout"
        uses: actions/checkout@v6

      # See https://github.com/marketplace/actions/setup-micromamba
      - name: setup-micromamba
        uses: mamba-org/setup-micromamba@v3.0.0
        with:
          environment-file: environment.yml
          environment-name: myria3d # activate the environment
          cache-environment: true
          cache-downloads: true
          generate-run-shell: true

      - name: "Build documentation"
        working-directory: ./docs/
        run: |
          # Tell torch_geometric where to find cuda
          export LD_LIBRARY_PATH="/usr/share/miniconda3/envs/myria3d/lib:$LD_LIBRARY_PATH"
          make html

      # 3. Déploy on Github Pages
      - name: "Deploy documentation on Github pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages # <- Branch where generated doc files will be commited
          # BRANCH: gh-pages-DEBUG    # <-- UNCOMMENT TO DEBUG DOCUMENTATION
          FOLDER: docs/build/html/ # <- Dir where .nojekyll is created and from which to deploy github pages.
